---
title: "Difference Scores with Difference Scores as Covariates"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
## Process and get data from common.R
source("common.R")
library(stargazer)
UDIO_DATASET_C <- UDIO_DATASET_C[UDIO_CONDITION != "Supported",]
UDIO_DATASET_C$DIFF_RC <- UDIO_DATASET_C$POST_RAPID_RC_AB - UDIO_DATASET_C$PRE_RAPID_RC_AB
UDIO_DATASET_C$DIFF_WIAT <- UDIO_DATASET_C$POST_WIAT_SS - UDIO_DATASET_C$PRE_WIAT_SS
UDIO_DATASET_C$DIFF_QRI <- UDIO_DATASET_C$POST_QRI_PCT - UDIO_DATASET_C$PRE_QRI_PCT
UDIO_DATASET_C$DIFF_WR <- UDIO_DATASET_C$POST_RAPID_WR_AB - UDIO_DATASET_C$PRE_RAPID_WR_AB
UDIO_DATASET_C$DIFF_SK <- UDIO_DATASET_C$POST_RAPID_SK_AB - UDIO_DATASET_C$PRE_RAPID_SK_AB
UDIO_DATASET_C$DIFF_VK <- UDIO_DATASET_C$POST_RAPID_VK_AB - UDIO_DATASET_C$PRE_RAPID_VK_AB
UDIO_DATASET_C$DIFF_MRQ <- UDIO_DATASET_C$POST_R_MRQ - UDIO_DATASET_C$PRE_R_MRQ
```

```{r rapid_rc, include=FALSE, echo=FALSE}
rc.dd.1 <- lmer(DIFF_RC ~ (1|CLASS_ID), data = UDIO_DATASET_C)
rc.dd.2 <- lmer(DIFF_RC ~ ELL + IEP + FARMS + (1|CLASS_ID), data = UDIO_DATASET_C)
rc.dd.3 <- lmer(DIFF_RC ~ ELL + IEP + FARMS + DIFF_VK + 
                     DIFF_SK + DIFF_WR + (1|CLASS_ID), data = UDIO_DATASET_C)
rc.dd.4 <- lmer(DIFF_RC ~ ELL + IEP + FARMS + DIFF_VK + 
                     DIFF_SK + DIFF_WR + DIFF_WIAT + (1|CLASS_ID), data = UDIO_DATASET_C)
rc.dd.5 <- lmer(DIFF_RC ~ ELL + IEP + FARMS + DIFF_VK + 
                     DIFF_SK + DIFF_WR + DIFF_WIAT + DIFF_MRQ + (1|CLASS_ID), data = UDIO_DATASET_C)
rc.dd.6 <- lmer(DIFF_RC ~ ELL + IEP + FARMS + DIFF_VK + 
                     DIFF_SK + DIFF_WR + DIFF_WIAT + DIFF_MRQ + UDIO_CONDITION + (1|CLASS_ID), data = UDIO_DATASET_C)
```

```{r rapid_rc.table, results="asis", echo=FALSE}
rc.dd <- list(rc.dd.1, rc.dd.2, rc.dd.3, rc.dd.4, rc.dd.5, rc.dd.6)
stargazer(rc.dd, title = "HLM Results for RAPID Reading Comprehension Difference Scores",
          dep.var.labels = "Reading Comp. (Post)",
          covariate.labels = c("Intercept", "ELL Status", "IEP Status", "Free/Reduced Lunch", "DIFF (VK)", "DIFF (SK)", "DIFF (WR)", "DIFF (WIAT)", "DIFF (MRQ)", "Udio Full"),
          header = F, type = "latex", intercept.bottom = FALSE,
          add.lines = varComp(rc.dd, 6), notes = "All predictors are grand-mean centered", notes.append = TRUE,
          table.placement = "h!")
```

```{r rapid_rc.diff, include = FALSE, echo=FALSE}
rc.dd.base <- lmer(DIFF_RC ~ ELL + IEP + FARMS + DIFF_VK + 
                     DIFF_SK + DIFF_WR + DIFF_WIAT + DIFF_MRQ + UDIO_CONDITION + (1|CLASS_ID), data = UDIO_DATASET_C)
rc.dd.i1 <- lmer(DIFF_RC ~ ELL + IEP + FARMS + DIFF_VK + 
                     DIFF_SK + DIFF_WR + DIFF_WIAT + DIFF_MRQ + UDIO_CONDITION + UDIO_CONDITION:ELL + (1|CLASS_ID), data = UDIO_DATASET_C)
rc.dd.i2 <- lmer(DIFF_RC ~ ELL + IEP + FARMS + DIFF_VK + 
                     DIFF_SK + DIFF_WR + DIFF_WIAT + DIFF_MRQ + UDIO_CONDITION + UDIO_CONDITION:IEP + (1|CLASS_ID), data = UDIO_DATASET_C)
rc.dd.i3 <- lmer(DIFF_RC ~ ELL + IEP + FARMS + DIFF_VK + 
                     DIFF_SK + DIFF_WR + DIFF_WIAT + DIFF_MRQ + UDIO_CONDITION + UDIO_CONDITION:FARMS + (1|CLASS_ID), data = UDIO_DATASET_C)


rc.dd.i4 <- lmer(DIFF_RC ~ ELL + IEP + FARMS + DIFF_VK + 
                     DIFF_SK + DIFF_WR + DIFF_WIAT + DIFF_MRQ + ELL:DIFF_VK + (1|CLASS_ID), data = UDIO_DATASET_C)
rc.dd.i5 <- lmer(DIFF_RC ~ ELL + IEP + FARMS + DIFF_VK + 
                     DIFF_SK + DIFF_WR + DIFF_WIAT + DIFF_MRQ + ELL:DIFF_SK + (1|CLASS_ID), data = UDIO_DATASET_C)
rc.dd.i6 <- lmer(DIFF_RC ~ ELL + IEP + FARMS + DIFF_VK + 
                     DIFF_SK + DIFF_WR + DIFF_WIAT + DIFF_MRQ + ELL:DIFF_WR + (1|CLASS_ID), data = UDIO_DATASET_C)

rc.dd.i7 <- lmer(DIFF_RC ~ ELL + IEP + FARMS + DIFF_VK + 
                     DIFF_SK + DIFF_WR + DIFF_WIAT + DIFF_MRQ + FARMS:DIFF_VK + (1|CLASS_ID), data = UDIO_DATASET_C)
rc.dd.i8 <- lmer(DIFF_RC ~ ELL + IEP + FARMS + DIFF_VK + 
                     DIFF_SK + DIFF_WR + DIFF_WIAT + DIFF_MRQ + FARMS:DIFF_SK + (1|CLASS_ID), data = UDIO_DATASET_C)
rc.dd.i9 <- lmer(DIFF_RC ~ ELL + IEP + FARMS + DIFF_VK + 
                     DIFF_SK + DIFF_WR + DIFF_WIAT + DIFF_MRQ + FARMS:DIFF_WR + (1|CLASS_ID), data = UDIO_DATASET_C)

rc.dd.i10 <- lmer(DIFF_RC ~ ELL + IEP + FARMS + DIFF_VK + 
                     DIFF_SK + DIFF_WR + DIFF_WIAT + DIFF_MRQ + IEP:DIFF_VK + (1|CLASS_ID), data = UDIO_DATASET_C)
rc.dd.i11 <- lmer(DIFF_RC ~ ELL + IEP + FARMS + DIFF_VK + 
                     DIFF_SK + DIFF_WR + DIFF_WIAT + DIFF_MRQ + IEP:DIFF_SK + (1|CLASS_ID), data = UDIO_DATASET_C)
rc.dd.i12 <- lmer(DIFF_RC ~ ELL + IEP + FARMS + DIFF_VK + 
                     DIFF_SK + DIFF_WR + DIFF_WIAT + DIFF_MRQ + IEP:DIFF_WR + (1|CLASS_ID), data = UDIO_DATASET_C)
```

Unfortunately, no significance was found in the model with WIAT difference score as the outcome

```{r wiat}
wiat.dd.1 <- lmer(DIFF_WIAT ~ (1|CLASS_ID), data = UDIO_DATASET_C)
wiat.dd.2 <- lmer(DIFF_WIAT ~ ELL + IEP + FARMS + (1|CLASS_ID), data = UDIO_DATASET_C)
wiat.dd.3 <- lmer(DIFF_WIAT ~ ELL + IEP + FARMS + KEY_MATCH_C + DIFF_VK + DIFF_SK + DIFF_WR + DIFF_RC + (1|CLASS_ID), data = UDIO_DATASET_C)
summary(wiat.dd.3)
```

```{r wiat_table, results="asis", echo=FALSE}
# wiat <- list(wiat.model.1, wiat.model.2, wiat.model.3, wiat.model.4, wiat.model.5, wiat.model.6)
# stargazer(wiat, title = "HLM Results for WIAT Standardized Scores",
#           dep.var.labels = "WIAT Standardized Score (Post)",
#           covariate.labels = c("Intercept", "WIAT SS (Pre)", "ELL Status", "IEP Status", "Free/Reduced Lunch", "Keyboarding", "Word Recog. (Post)", "Voc. Know. (Post)", "Syn. Know. (Post)", "Reading Comp. (Post)", "RC x IEP"), 
#           header = F, type = "latex", intercept.bottom = FALSE,
#           add.lines = varComp(wiat), notes = "All predictors are grand-mean centered", notes.append = TRUE)
```

```{r qri, echo = FALSE, include = FALSE}
# qri.model.1 <- lmer(DIFF_QRI ~ (1|CLASS_ID), data = UDIO_DATASET_C)
# qri.model.2 <- lmer(DIFF_QRI ~ ELL + IEP + FARMS + (1|CLASS_ID), data = UDIO_DATASET_C)
# qri.model.3 <- lmer(DIFF_QRI ~ ELL + IEP + FARMS + PRE_QRI_PCT_C + POST_RAPID_WR_AB_C + POST_RAPID_VK_AB_C + POST_RAPID_SK_AB_C + POST_RAPID_RC_AB_C + (1|CLASS_ID), data = UDIO_DATASET_C)
# qri.model.4 <- lmer(DIFF_QRI ~ ELL + IEP + FARMS + PRE_QRI_PCT_C + POST_RAPID_WR_AB_C + POST_RAPID_VK_AB_C + POST_RAPID_RC_AB_C + POST_WIAT_SS_C + (1|CLASS_ID), data = UDIO_DATASET_C)
# qri.model.5 <- lmer(DIFF_QRI ~ ELL + IEP + FARMS + PRE_QRI_PCT_C + POST_RAPID_WR_AB_C + POST_RAPID_VK_AB_C +  POST_RAPID_RC_AB_C + POST_WIAT_SS_C + KEY_MATCH_C + (1|CLASS_ID), data = UDIO_DATASET_C)
```

```{r qri_table, results="asis", echo=FALSE}
# qri <- list(qri.model.1, qri.model.2, qri.model.3, qri.model.4, qri.model.5)
# stargazer(qri, title = "HLM models for QRI Percentatge Score (Post)",
#           dep.var.labels = "Percentage Score for QRI (Post)",
#           covariate.labels = c("Intercept", "ELL Status", "IEP Status", "Free/Reduced Lunch", "QRI (Pre)", "Word Recog. (Post)", "Voc. Know. (Post)", "Syn. Know. (Post)", "Reading Comp. (Post)", "WIAT SS (Post)", "Keyboarding"), 
#           header = F, type = "latex", intercept.bottom = FALSE,
#           add.lines = varComp(qri), notes = "All predictors are grand-mean centered", notes.append = TRUE)
```


```{r mrq, echo = FALSE, include=FALSE}
# mrq.model.1 <- lmer(POST_R_MRQ ~ (1|CLASS_ID), data = UDIO_DATASET_C)
# mrq.model.2 <- lmer(POST_R_MRQ ~ ELL + IEP + FARMS + (1|CLASS_ID), data = UDIO_DATASET_C)
# mrq.model.3 <- lmer(POST_R_MRQ ~ ELL + IEP + FARMS + PRE_R_MRQ_C + POST_RAPID_WR_AB_C + POST_RAPID_VK_AB_C + + POST_RAPID_SK_AB_C + POST_RAPID_RC_AB_C + (1|CLASS_ID), data = UDIO_DATASET_C)
# mrq.model.4 <- lmer(POST_R_MRQ ~ ELL + IEP + FARMS + PRE_R_MRQ_C + UDIO_CONDITION + (1|CLASS_ID), data = UDIO_DATASET_C)
# mrq.model.5 <- lmer(POST_R_MRQ ~ ELL + IEP + FARMS + PRE_R_MRQ_C + UDIO_CONDITION + POST_WIAT_SS_C + (1|CLASS_ID), data = UDIO_DATASET_C)
```

```{r mrq_table, results="asis", echo=FALSE, include=FALSE}
# mrq <- list(mrq.model.1, mrq.model.2, mrq.model.3, mrq.model.4, mrq.model.5)
# stargazer(mrq, title = "HLM models for MRQ (Post)",
#           dep.var.labels = "Average Score for MRQ (Post)",
#           covariate.labels = c("Intercept", "ELL Status", "IEP Status", "Free/Reduced Lunch", "Reading MRQ (Pre)", "Word Recog. (Post)", "Voc. Know. (Post)", "Syn. Know. (Post)", "Reading Comp. (Post)", "Full", "Supported", "WIAT SS (Post)"), 
#           header = F, type = "latex", intercept.bottom = FALSE,
#           add.lines = varComp(mrq), notes = "All predictors are grand-mean centered", notes.append = TRUE)
```
