---
title: "HLM_Random_Effects"
author: "Paul Xu"
date: "10/13/2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("common.R")
UDIO_DATASET_C <- UDIO_DATASET_C[UDIO_CONDITION != "Supported",]
```

### Part 1. Comparison of HLM Models with different Random Effects (RAPID RC)

```{r rapid_rc}

#### Baseline Model
rc.model.5 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C + ELL + IEP + FARMS + POST_RAPID_WR_AB_C + 
                     POST_RAPID_VK_AB_C + POST_RAPID_SK_AB_C + POST_WIAT_SS_C + (1|CLASS_ID), data = UDIO_DATASET_C)

#### Adding different random effects
rc.model.6 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C + ELL + IEP + FARMS + POST_RAPID_WR_AB_C +
                     POST_RAPID_VK_AB_C + POST_RAPID_SK_AB_C + POST_WIAT_SS_C + UDIO_CONDITION + (1|CLASS_ID), data = UDIO_DATASET_C)

rc.model.7 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C + ELL + IEP + FARMS + POST_RAPID_WR_AB_C +
                     POST_RAPID_VK_AB_C + POST_RAPID_SK_AB_C + POST_WIAT_SS_C + UDIO_CONDITION:PRE_RAPID_RC_AB_C + (1|CLASS_ID), data = UDIO_DATASET_C)

rc.model.8 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C + ELL + IEP + FARMS + POST_RAPID_WR_AB_C +
                     POST_RAPID_VK_AB_C + POST_RAPID_SK_AB_C + POST_WIAT_SS_C + UDIO_CONDITION + UDIO_CONDITION:ELL + (1|CLASS_ID), data = UDIO_DATASET_C)

rc.model.9 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C + ELL + IEP + FARMS + POST_RAPID_WR_AB_C +
                     POST_RAPID_VK_AB_C + POST_RAPID_SK_AB_C + POST_WIAT_SS_C + UDIO_CONDITION + UDIO_CONDITION:IEP + (1|CLASS_ID), data = UDIO_DATASET_C)

rc.model.10 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C + ELL + IEP + FARMS + POST_RAPID_WR_AB_C +
                     POST_RAPID_VK_AB_C + POST_RAPID_SK_AB_C + POST_WIAT_SS_C + UDIO_CONDITION + UDIO_CONDITION:FARMS + (1|CLASS_ID), data = UDIO_DATASET_C)

rc.model.11 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C + ELL + IEP + FARMS + POST_RAPID_WR_AB_C +
                     POST_RAPID_VK_AB_C + POST_RAPID_SK_AB_C + POST_WIAT_SS_C + PRE_RAPID_RC_AB_C:ELL + (1|CLASS_ID), data = UDIO_DATASET_C)

rc.model.12 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C + ELL + IEP + FARMS + POST_RAPID_WR_AB_C +
                     POST_RAPID_VK_AB_C + POST_RAPID_SK_AB_C + POST_WIAT_SS_C + PRE_RAPID_RC_AB_C:IEP + (1|CLASS_ID), data = UDIO_DATASET_C)

rc.model.13 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C + ELL + IEP + FARMS + POST_RAPID_WR_AB_C +
                     POST_RAPID_VK_AB_C + POST_RAPID_SK_AB_C + POST_WIAT_SS_C + PRE_RAPID_RC_AB_C:FARMS + (1|CLASS_ID), data = UDIO_DATASET_C)

rc.model.14 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C + ELL + IEP + FARMS + POST_RAPID_WR_AB_C +
                     POST_RAPID_VK_AB_C + POST_RAPID_SK_AB_C + POST_WIAT_SS_C + POST_WIAT_SS_C:ELL + (1|CLASS_ID), data = UDIO_DATASET_C)

rc.model.15 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C + ELL + IEP + FARMS + POST_RAPID_WR_AB_C +
                     POST_RAPID_VK_AB_C + POST_RAPID_SK_AB_C + POST_WIAT_SS_C + POST_WIAT_SS_C:IEP + (1|CLASS_ID), data = UDIO_DATASET_C)

rc.model.16 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C + ELL + IEP + FARMS + POST_RAPID_WR_AB_C +
                     POST_RAPID_VK_AB_C + POST_RAPID_SK_AB_C + POST_WIAT_SS_C + POST_WIAT_SS_C:FARMS + (1|CLASS_ID), data = UDIO_DATASET_C)

#################################

rc.model.pre.1 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C + ELL + IEP + FARMS + PRE_RAPID_WR_AB_C +
                     PRE_RAPID_VK_AB_C + PRE_RAPID_SK_AB_C + PRE_WIAT_SS_C + PRE_R_MRQ_C + UDIO_CONDITION + PRE_R_MRQ_C:UDIO_CONDITION + (1|CLASS_ID), data = UDIO_DATASET_C)

rc.model.pre.2 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C + ELL + IEP + FARMS + PRE_RAPID_WR_AB_C +
                     PRE_RAPID_VK_AB_C + PRE_RAPID_SK_AB_C + PRE_WIAT_SS_C + PRE_R_MRQ_C + UDIO_CONDITION + PRE_R_MRQ_C:UDIO_CONDITION + (1|CLASS_ID), data = UDIO_DATASET_C)

rc.model.pre.3 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C + ELL + IEP + FARMS + PRE_RAPID_WR_AB_C +
                     PRE_RAPID_VK_AB_C + PRE_RAPID_SK_AB_C + PRE_WIAT_SS_C + PRE_R_MRQ_C + UDIO_CONDITION + PRE_RAPID_WR_AB_C:UDIO_CONDITION + (1|CLASS_ID), data = UDIO_DATASET_C)

rc.model.pre.4 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C + ELL + IEP + FARMS + PRE_RAPID_WR_AB_C +
                     PRE_RAPID_VK_AB_C + PRE_RAPID_SK_AB_C + PRE_WIAT_SS_C + PRE_R_MRQ_C + UDIO_CONDITION + PRE_RAPID_SK_AB_C:UDIO_CONDITION + (1|CLASS_ID), data = UDIO_DATASET_C)

rc.model.pre.5 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C + ELL + IEP + FARMS + PRE_RAPID_WR_AB_C +
                     PRE_RAPID_VK_AB_C + PRE_RAPID_SK_AB_C + PRE_WIAT_SS_C + PRE_R_MRQ_C + UDIO_CONDITION + PRE_RAPID_VK_AB_C:UDIO_CONDITION + (1|CLASS_ID), data = UDIO_DATASET_C)

rc.model.pre.6 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C + ELL + IEP + FARMS + PRE_RAPID_WR_AB_C +
                     PRE_RAPID_VK_AB_C + PRE_RAPID_SK_AB_C + PRE_WIAT_SS_C + PRE_R_MRQ_C + UDIO_CONDITION + PRE_WIAT_SS_C:UDIO_CONDITION + (1|CLASS_ID), data = UDIO_DATASET_C)

rc.model.pre.7 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C + ELL + IEP + FARMS + PRE_RAPID_WR_AB_C +
                     PRE_RAPID_VK_AB_C + PRE_RAPID_SK_AB_C + PRE_WIAT_SS_C + PRE_R_MRQ_C + UDIO_CONDITION + ELL:UDIO_CONDITION + (1|CLASS_ID), data = UDIO_DATASET_C)

rc.model.pre.8 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C + ELL + IEP + FARMS + PRE_RAPID_WR_AB_C +
                     PRE_RAPID_VK_AB_C + PRE_RAPID_SK_AB_C + PRE_WIAT_SS_C + PRE_R_MRQ_C + UDIO_CONDITION + IEP:UDIO_CONDITION + (1|CLASS_ID), data = UDIO_DATASET_C)

rc.model.pre.9 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C + ELL + IEP + FARMS + PRE_RAPID_WR_AB_C +
                     PRE_RAPID_VK_AB_C + PRE_RAPID_SK_AB_C + PRE_WIAT_SS_C + PRE_R_MRQ_C + UDIO_CONDITION + FARMS:UDIO_CONDITION + (1|CLASS_ID), data = UDIO_DATASET_C)

rc.model.pre.10 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C + ELL + IEP + FARMS + PRE_RAPID_WR_AB_C +
                     PRE_RAPID_VK_AB_C + PRE_RAPID_SK_AB_C + PRE_WIAT_SS_C + PRE_R_MRQ_C + PRE_RAPID_RC_AB_C:ELL + (1|CLASS_ID), data = UDIO_DATASET_C)

rc.model.pre.11 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C +ELL + IEP + FARMS + PRE_RAPID_WR_AB_C +
                     PRE_RAPID_VK_AB_C + PRE_RAPID_SK_AB_C + PRE_WIAT_SS_C + PRE_R_MRQ_C + PRE_RAPID_RC_AB_C:IEP + (1|CLASS_ID), data = UDIO_DATASET_C)

rc.model.pre.12 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C +ELL + IEP + FARMS + PRE_RAPID_WR_AB_C +
                     PRE_RAPID_VK_AB_C + PRE_RAPID_SK_AB_C + PRE_WIAT_SS_C + PRE_RAPID_RC_AB_C:FARMS + (1|CLASS_ID), data = UDIO_DATASET_C)

rc.model.pre.13 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C +ELL + IEP + FARMS + PRE_RAPID_WR_AB_C +
                     PRE_RAPID_VK_AB_C + PRE_RAPID_SK_AB_C + PRE_WIAT_SS_C + PRE_R_MRQ_C + (1|CLASS_ID), data = UDIO_DATASET_C)

rc.model.pre.14 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C + ELL + IEP + FARMS + PRE_RAPID_WR_AB_C +
                     PRE_RAPID_VK_AB_C + PRE_RAPID_SK_AB_C + PRE_WIAT_SS_C + PRE_R_MRQ_C + PRE_RAPID_RC_AB_C:ELL + (1|CLASS_ID), data = UDIO_DATASET_C)

rc.model.pre.15 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C + ELL + IEP + FARMS + PRE_RAPID_WR_AB_C +
                     PRE_RAPID_VK_AB_C + PRE_RAPID_SK_AB_C + PRE_WIAT_SS_C + PRE_R_MRQ_C + PRE_RAPID_RC_AB_C:FARMS + (1|CLASS_ID), data = UDIO_DATASET_C)

rc.model.pre.16 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C + ELL + IEP + FARMS + PRE_RAPID_WR_AB_C +
                     PRE_RAPID_VK_AB_C + PRE_RAPID_SK_AB_C + PRE_WIAT_SS_C + PRE_R_MRQ_C + PRE_RAPID_RC_AB_C:IEP + (1|CLASS_ID), data = UDIO_DATASET_C)

rc.model.pre.17 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C + ELL + IEP + FARMS + PRE_RAPID_WR_AB_C +
                     PRE_RAPID_VK_AB_C + PRE_RAPID_SK_AB_C + PRE_WIAT_SS_C + PRE_R_MRQ_C + PRE_RAPID_RC_AB_C:FARMS + + PRE_WIAT_SS_C:ELL + (1|CLASS_ID), data = UDIO_DATASET_C)

rc.model.pre.18 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C + ELL + IEP + FARMS + PRE_RAPID_WR_AB_C +
                     PRE_RAPID_VK_AB_C + PRE_RAPID_SK_AB_C + PRE_WIAT_SS_C + PRE_R_MRQ_C + PRE_RAPID_RC_AB_C:FARMS + + PRE_WIAT_SS_C:IEP + (1|CLASS_ID), data = UDIO_DATASET_C)

rc.model.pre.19 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C + ELL + IEP + FARMS + PRE_RAPID_WR_AB_C +
                     PRE_RAPID_VK_AB_C + PRE_RAPID_SK_AB_C + PRE_WIAT_SS_C + PRE_R_MRQ_C + PRE_RAPID_RC_AB_C:FARMS + + PRE_WIAT_SS_C:FARMS + (1|CLASS_ID), data = UDIO_DATASET_C)

rc.model.pre.20 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C + ELL + IEP + FARMS + PRE_RAPID_WR_AB_C +
                     PRE_RAPID_VK_AB_C + PRE_RAPID_SK_AB_C + PRE_WIAT_SS_C + PRE_R_MRQ_C + PRE_RAPID_RC_AB_C:FARMS + + PRE_R_MRQ_C:ELL + (1|CLASS_ID), data = UDIO_DATASET_C)

rc.model.pre.21 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C + ELL + IEP + FARMS + PRE_RAPID_WR_AB_C +
                     PRE_RAPID_VK_AB_C + PRE_RAPID_SK_AB_C + PRE_WIAT_SS_C + PRE_R_MRQ_C + PRE_RAPID_RC_AB_C:FARMS + + PRE_R_MRQ_C:IEP + (1|CLASS_ID), data = UDIO_DATASET_C)

rc.model.pre.22 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C + ELL + IEP + FARMS + PRE_RAPID_WR_AB_C +
                     PRE_RAPID_VK_AB_C + PRE_RAPID_SK_AB_C + PRE_WIAT_SS_C + PRE_R_MRQ_C + PRE_RAPID_RC_AB_C:FARMS + + PRE_R_MRQ_C:FARMS + (1|CLASS_ID), data = UDIO_DATASET_C)

rc.model.pre.23 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C + ELL + IEP + FARMS + PRE_RAPID_WR_AB_C +
                     PRE_RAPID_VK_AB_C + PRE_RAPID_SK_AB_C + PRE_WIAT_SS_C + PRE_R_MRQ_C + PRE_RAPID_RC_AB_C:FARMS + + PRE_R_MRQ_C:FARMS + PRE_R_MRQ_C:FARMS:PRE_RAPID_RC_AB + (1|CLASS_ID), data = UDIO_DATASET_C)

rc.model.pre.24 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C + ELL + IEP + FARMS + PRE_RAPID_WR_AB_C +
                     PRE_RAPID_VK_AB_C + PRE_RAPID_SK_AB_C + PRE_WIAT_SS_C + PRE_R_MRQ_C + PRE_RAPID_RC_AB_C:FARMS + + PRE_R_MRQ_C:FARMS + PRE_R_MRQ_C:FARMS:PRE_RAPID_RC_AB + PRE_RAPID_WR_AB_C:ELL + (1|CLASS_ID), data = UDIO_DATASET_C)

rc.model.pre.25 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C + ELL + IEP + FARMS + PRE_RAPID_WR_AB_C +
                     PRE_RAPID_VK_AB_C + PRE_RAPID_SK_AB_C + PRE_WIAT_SS_C + PRE_R_MRQ_C + PRE_RAPID_RC_AB_C:FARMS + + PRE_R_MRQ_C:FARMS + PRE_R_MRQ_C:FARMS:PRE_RAPID_RC_AB + PRE_RAPID_WR_AB_C:IEP + (1|CLASS_ID), data = UDIO_DATASET_C)

rc.model.pre.26 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C + ELL + IEP + FARMS + PRE_RAPID_WR_AB_C +
                     PRE_RAPID_VK_AB_C + PRE_RAPID_SK_AB_C + PRE_WIAT_SS_C + PRE_R_MRQ_C + PRE_RAPID_RC_AB_C:FARMS + + PRE_R_MRQ_C:FARMS + PRE_R_MRQ_C:FARMS:PRE_RAPID_RC_AB + PRE_RAPID_WR_AB_C:FARMS + (1|CLASS_ID), data = UDIO_DATASET_C)

rc.model.pre.27 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C + ELL + IEP + FARMS + PRE_RAPID_WR_AB_C +
                     PRE_RAPID_VK_AB_C + PRE_RAPID_SK_AB_C + PRE_WIAT_SS_C + PRE_R_MRQ_C + PRE_RAPID_RC_AB_C:FARMS + + PRE_R_MRQ_C:FARMS + PRE_R_MRQ_C:FARMS:PRE_RAPID_RC_AB + PRE_RAPID_SK_AB_C:ELL + (1|CLASS_ID), data = UDIO_DATASET_C)

rc.model.pre.28 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C + ELL + IEP + FARMS + PRE_RAPID_WR_AB_C +
                     PRE_RAPID_VK_AB_C + PRE_RAPID_SK_AB_C + PRE_WIAT_SS_C + PRE_R_MRQ_C + PRE_RAPID_RC_AB_C:FARMS + + PRE_R_MRQ_C:FARMS + PRE_R_MRQ_C:FARMS:PRE_RAPID_RC_AB + PRE_RAPID_SK_AB_C:IEP + (1|CLASS_ID), data = UDIO_DATASET_C)

rc.model.pre.29 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C + ELL + IEP + FARMS + PRE_RAPID_WR_AB_C +
                     PRE_RAPID_VK_AB_C + PRE_RAPID_SK_AB_C + PRE_WIAT_SS_C + PRE_R_MRQ_C + PRE_RAPID_RC_AB_C:FARMS + + PRE_R_MRQ_C:FARMS + PRE_R_MRQ_C:FARMS:PRE_RAPID_RC_AB + PRE_RAPID_SK_AB_C:FARMS + (1|CLASS_ID), data = UDIO_DATASET_C)

rc.model.pre.30 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C + ELL + IEP + FARMS + PRE_RAPID_WR_AB_C +
                     PRE_RAPID_VK_AB_C + PRE_RAPID_SK_AB_C + PRE_WIAT_SS_C + PRE_R_MRQ_C + PRE_RAPID_RC_AB_C:FARMS + + PRE_R_MRQ_C:FARMS + PRE_R_MRQ_C:FARMS:PRE_RAPID_RC_AB + PRE_RAPID_VK_AB_C:ELL + (1|CLASS_ID), data = UDIO_DATASET_C)

rc.model.pre.31 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C + ELL + IEP + FARMS + PRE_RAPID_WR_AB_C +
                     PRE_RAPID_VK_AB_C + PRE_RAPID_SK_AB_C + PRE_WIAT_SS_C + PRE_R_MRQ_C + PRE_RAPID_RC_AB_C:FARMS + + PRE_R_MRQ_C:FARMS + PRE_R_MRQ_C:FARMS:PRE_RAPID_RC_AB + PRE_RAPID_VK_AB_C:IEP + (1|CLASS_ID), data = UDIO_DATASET_C)

rc.model.pre.32 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C + ELL + IEP + FARMS + PRE_RAPID_WR_AB_C +
                     PRE_RAPID_VK_AB_C + PRE_RAPID_SK_AB_C + PRE_WIAT_SS_C + PRE_R_MRQ_C + PRE_RAPID_RC_AB_C:FARMS + + PRE_R_MRQ_C:FARMS + PRE_R_MRQ_C:FARMS:PRE_RAPID_RC_AB + PRE_RAPID_VK_AB_C:FARMS + (1|CLASS_ID), data = UDIO_DATASET_C)


rc.model.pre.33 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C + ELL + IEP + FARMS + PRE_RAPID_WR_AB_C +
                     PRE_RAPID_VK_AB_C + PRE_RAPID_SK_AB_C + PRE_WIAT_SS_C + PRE_R_MRQ_C + PRE_RAPID_RC_AB_C:FARMS + + PRE_WIAT_SS_C:FARMS + (1|CLASS_ID), data = UDIO_DATASET_C)

rc.model.pre.34 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C + ELL + IEP + FARMS + PRE_RAPID_WR_AB_C +
                     PRE_RAPID_VK_AB_C + PRE_RAPID_SK_AB_C + PRE_WIAT_SS_C + PRE_R_MRQ_C + PRE_RAPID_RC_AB_C:FARMS + + PRE_WIAT_SS_C:IEP + (1|CLASS_ID), data = UDIO_DATASET_C)

rc.model.pre.35 <- lmer(POST_RAPID_RC_AB ~ PRE_RAPID_RC_AB_C + ELL + IEP + FARMS + PRE_RAPID_WR_AB_C +
                     PRE_RAPID_VK_AB_C + PRE_RAPID_SK_AB_C + PRE_WIAT_SS_C + PRE_R_MRQ_C + PRE_RAPID_RC_AB_C:FARMS + + PRE_WIAT_SS_C:ELL + (1|CLASS_ID), data = UDIO_DATASET_C)
```

### Part 2. WIAT

```{r wiat}
# Baseline model
wiat.model.5 <- lmer(POST_WIAT_SS ~ PRE_WIAT_SS_C + ELL + IEP + FARMS + KEY_MATCH_C + POST_RAPID_VK_AB_C + POST_RAPID_RC_AB_C + (1|CLASS_ID), data = UDIO_DATASET_C)

# Adding Random Effects
wiat.model.6 <- lmer(POST_WIAT_SS ~ PRE_WIAT_SS_C + ELL + IEP + FARMS + KEY_MATCH_C + POST_RAPID_VK_AB_C + POST_RAPID_RC_AB_C + UDIO_CONDITION + (1|CLASS_ID), data = UDIO_DATASET_C)

wiat.model.7 <- lmer(POST_WIAT_SS ~ PRE_WIAT_SS_C + ELL + IEP + FARMS + KEY_MATCH_C + POST_RAPID_VK_AB_C + POST_RAPID_RC_AB_C + UDIO_CONDITION + UDIO_CONDITION:ELL + (1|CLASS_ID), data = UDIO_DATASET_C)

wiat.model.8 <- lmer(POST_WIAT_SS ~ PRE_WIAT_SS_C + ELL + IEP + FARMS + KEY_MATCH_C + POST_RAPID_VK_AB_C + POST_RAPID_RC_AB_C + UDIO_CONDITION + UDIO_CONDITION:IEP + (1|CLASS_ID), data = UDIO_DATASET_C)

wiat.model.9 <- lmer(POST_WIAT_SS ~ PRE_WIAT_SS_C + ELL + IEP + FARMS + KEY_MATCH_C + POST_RAPID_VK_AB_C + POST_RAPID_RC_AB_C + UDIO_CONDITION + UDIO_CONDITION:FARMS + (1|CLASS_ID), data = UDIO_DATASET_C)

wiat.model.10 <- lmer(POST_WIAT_SS ~ PRE_WIAT_SS_C + ELL + IEP + FARMS + KEY_MATCH_C + POST_RAPID_VK_AB_C + POST_RAPID_RC_AB_C + UDIO_CONDITION + UDIO_CONDITION:PRE_WIAT_SS_C + (1|CLASS_ID), data = UDIO_DATASET_C)

wiat.model.11 <- lmer(POST_WIAT_SS ~ PRE_WIAT_SS_C + ELL + IEP + FARMS + KEY_MATCH_C + POST_RAPID_VK_AB_C + POST_RAPID_RC_AB_C + PRE_WIAT_SS_C:ELL+ (1|CLASS_ID), data = UDIO_DATASET_C)

wiat.model.12 <- lmer(POST_WIAT_SS ~ PRE_WIAT_SS_C + ELL + IEP + FARMS + KEY_MATCH_C + POST_RAPID_VK_AB_C + POST_RAPID_RC_AB_C + PRE_WIAT_SS_C:IEP+ (1|CLASS_ID), data = UDIO_DATASET_C)

wiat.model.13 <- lmer(POST_WIAT_SS ~ PRE_WIAT_SS_C + ELL + IEP + FARMS + KEY_MATCH_C + POST_RAPID_VK_AB_C + POST_RAPID_RC_AB_C + PRE_WIAT_SS_C:FARMS+ (1|CLASS_ID), data = UDIO_DATASET_C)

wiat.model.14 <- lmer(POST_WIAT_SS ~ PRE_WIAT_SS_C + ELL + IEP + FARMS + KEY_MATCH_C + POST_RAPID_VK_AB_C + POST_RAPID_RC_AB_C + POST_RAPID_RC_AB_C:ELL+ (1|CLASS_ID), data = UDIO_DATASET_C)

wiat.model.15 <- lmer(POST_WIAT_SS ~ PRE_WIAT_SS_C + ELL + IEP + FARMS + KEY_MATCH_C + POST_RAPID_VK_AB_C + POST_RAPID_RC_AB_C + POST_RAPID_RC_AB_C:IEP+ (1|CLASS_ID), data = UDIO_DATASET_C)

wiat.model.16 <- lmer(POST_WIAT_SS ~ PRE_WIAT_SS_C + ELL + IEP + FARMS + KEY_MATCH_C + POST_RAPID_VK_AB_C + POST_RAPID_RC_AB_C + POST_RAPID_RC_AB_C:FARMS+ (1|CLASS_ID), data = UDIO_DATASET_C)
```

### Part 3. QRI

```{r}
# Baseline model
qri.model.5 <- lmer(POST_QRI_PCT ~  + PRE_QRI_PCT_C + ELL + IEP + FARMS + POST_RAPID_WR_AB_C + POST_RAPID_VK_AB_C +  POST_RAPID_RC_AB_C + POST_WIAT_SS_C + KEY_MATCH_C + (1|CLASS_ID), data = UDIO_DATASET_C)

# Add random effects
qri.model.6 <- lmer(POST_QRI_PCT ~ PRE_QRI_PCT_C + ELL + IEP + FARMS + POST_RAPID_WR_AB_C + POST_RAPID_VK_AB_C +  POST_RAPID_RC_AB_C + POST_WIAT_SS_C + KEY_MATCH_C + UDIO_CONDITION + UDIO_CONDITION:PRE_QRI_PCT_C + (1|CLASS_ID), data = UDIO_DATASET_C)

qri.model.7 <- lmer(POST_QRI_PCT ~ PRE_QRI_PCT_C + ELL + IEP + FARMS + POST_RAPID_WR_AB_C + POST_RAPID_VK_AB_C +  POST_RAPID_RC_AB_C + POST_WIAT_SS_C + KEY_MATCH_C + UDIO_CONDITION + UDIO_CONDITION:IEP + (1|CLASS_ID), data = UDIO_DATASET_C)

qri.model.8 <- lmer(POST_QRI_PCT ~ PRE_QRI_PCT_C + ELL + IEP + FARMS + POST_RAPID_WR_AB_C + POST_RAPID_VK_AB_C +  POST_RAPID_RC_AB_C + POST_WIAT_SS_C + KEY_MATCH_C + UDIO_CONDITION + UDIO_CONDITION:FARMS + (1|CLASS_ID), data = UDIO_DATASET_C)

qri.model.9 <- lmer(POST_QRI_PCT ~ PRE_QRI_PCT_C + ELL + IEP + FARMS + POST_RAPID_WR_AB_C + POST_RAPID_VK_AB_C +  POST_RAPID_RC_AB_C + POST_WIAT_SS_C + KEY_MATCH_C + UDIO_CONDITION + UDIO_CONDITION:ELL + (1|CLASS_ID), data = UDIO_DATASET_C)
```

```{r interaction}
interaction.df <- UDIO_DATASET_C %>%
  select(ID, CLASS_ID, IEP, ELL, FARMS, UDIO_CONDITION, PRE_QRI_PCT, POST_QRI_PCT) %>%
  gather(TIME, SCORE, PRE_QRI_PCT, POST_QRI_PCT) %>%
  mutate(TIME = factor(TIME, levels = c("PRE_QRI_PCT", "POST_QRI_PCT")))


p1 <- ggplot(interaction.df[!is.na(interaction.df$IEP),], aes(TIME, SCORE, group = IEP, linetype = IEP)) + geom_line(stat ="summary", fun.y = "mean") + facet_wrap(~UDIO_CONDITION)
p2 <-  ggplot(interaction.df, aes(TIME, SCORE, group = ELL, linetype = ELL)) + geom_line(stat ="summary", fun.y = "mean") + facet_wrap(~UDIO_CONDITION)
p3 <- ggplot(interaction.df, aes(TIME, SCORE, group = FARMS, linetype = FARMS)) + geom_line(stat ="summary", fun.y = "mean") + facet_wrap(~UDIO_CONDITION)
```

